function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(4)=1;
    ys_(3)=((1-params(2)*(1-params(3)))/(ys_(4)*params(2)*params(1)))^(1/(params(1)-1));
    ys_(1)=ys_(4)*ys_(3)^params(1);
    ys_(2)=ys_(1)-params(3)*ys_(3);
    % Auxiliary equations
end
