function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(8)=1;
    ys_(6)=params(3);
    ys_(7)=params(6);
    ys_(4)=((1-params(4))*(params(4)/(params(3)+params(2)))^(params(4)/(1-params(4))))^(1/(params(5)-1));
    ys_(5)=ys_(4)*(params(4)/(params(3)+params(2)))^(1/(1-params(4)));
    ys_(1)=ys_(5)^params(4)*ys_(4)^(1-params(4));
    ys_(3)=params(2)*ys_(5);
    ys_(2)=ys_(1)-ys_(3)-params(3)*ys_(7);
    ys_(10)=exp(ys_(1)-ys_(2)-ys_(3));
    ys_(9)=exp(log(ys_(10))/ys_(1));
    ys_(11)=1;
    ys_(12)=exp(log(ys_(11))/ys_(1));
    ys_(14)=(ys_(2)-1/params(5)*ys_(4)^params(5))^(-params(1));
    ys_(13)=ys_(14);
    ys_(15)=ys_(1)*(1-params(4))*ys_(13)/ys_(4);
    % Auxiliary equations
end
